### ISSUE TITLE
Indices off by one

### ISSUE THREAD

**Issue by eezstreet** [kambala-decapitator/QTblEditor#1]
As an example, go to index 5360 in string.tbl. In AFJ's TBL Editor, it will read:

`Versions do not match. Please log onto battle.net or go to http://www.blizzard.com/support/Diablo2 to get a patch`

In QTblEditor it will read:

`A dead hardcore character cannot join or create any games.`

**Comment by kambala-decapitator** [comment]
There's already an option to toggle between 0/1 rows. Also added respecting this setting in the Go To dialog.
